services:
    frontend:
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
            target: dev
        restart: unless-stopped
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            VITE_API_URL: ${VITE_API_URL}
        ports:
            - 5173:5173
    mock:
        build: docker/mock/
        working_dir: /app
        command: 'json-server --host 0.0.0.0 ./mock/database.js --routes ./mock/routes.json --config ./mock/server.json'
        volumes:
            - ./mock:/app/mock
        ports:
            - 5001:5001
