name: CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.1

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: docker/frontend/Dockerfile
          push: true
          target: prod
          platforms: linux/amd64
          tags: |
            ${{ secrets.USER }}/frontend:v1
            ${{ secrets.USER }}/frontend:latest
